---
oh_my_zsh_enable: false
oh_my_zsh_target_user: >-
  {{
    base_admin_user
    | default(lookup('ansible.builtin.env', 'INFRA_ADMIN_USER') | default('openclaw', true))
  }}

oh_my_zsh_repo: https://github.com/ohmyzsh/ohmyzsh.git
oh_my_zsh_repo_version: master
oh_my_zsh_shell_path: /bin/zsh

oh_my_zsh_theme_name: guru2
oh_my_zsh_theme_url: https://gist.githubusercontent.com/lukeharvey/992fca16c6f5d1b66f75b9e1b17ab308/raw/guru2.zsh-theme
oh_my_zsh_plugins:
  - git

oh_my_zsh_install_z: true
oh_my_zsh_z_url: https://raw.githubusercontent.com/rupa/z/master/z.sh
