---
cloudflare_enable: false

cloudflare_install_origin_ca_root: true
cloudflare_origin_ca_root_type: rsa
cloudflare_origin_ca_root_urls:
  rsa: https://developers.cloudflare.com/ssl/static/origin_ca_rsa_root.pem
  ecc: https://developers.cloudflare.com/ssl/static/origin_ca_ecc_root.pem

cloudflare_zone_id: "{{ lookup('ansible.builtin.env', 'CLOUDFLARE_ZONE_ID') | default('', true) }}"
cloudflare_zone_name: "{{ lookup('ansible.builtin.env', 'CLOUDFLARE_ZONE_NAME') | default('', true) }}"
cloudflare_email: "{{ lookup('ansible.builtin.env', 'CLOUDFLARE_EMAIL') | default('', true) }}"
cloudflare_global_api_key: "{{ lookup('ansible.builtin.env', 'CLOUDFLARE_GLOBAL_API_KEY') | default('', true) }}"
cloudflare_dns_api_token: "{{ lookup('ansible.builtin.env', 'CLOUDFLARE_DNS_API_TOKEN') | default('', true) }}"

cloudflare_manage_ssl_mode: false
cloudflare_ssl_mode: strict

cloudflare_manage_dns: false
cloudflare_dns_default_ttl: 1
cloudflare_dns_default_proxied: false
cloudflare_dns_records: []
