---
driver:
  name: vagrant

platforms:
  - name: ubuntu2404-vagrant
    box: hashicorp-education/ubuntu-24-04
    provider_name: virtualbox
    provider_options:
      memory: 2048
      cpus: 2

provisioner:
  name: ansible
  log: true
  env:
    ANSIBLE_LIBRARY: ${MOLECULE_PROJECT_DIRECTORY}/molecule/vagrant/library
  playbooks:
    converge: converge.yml
    verify: verify.yml

scenario:
  name: vagrant
  test_sequence:
    - destroy
    - create
    - converge
    - idempotence
    - verify
    - destroy

verifier:
  name: ansible
