---
socket_proxy_enable: false

socket_proxy_install_docker: true
socket_proxy_stack_root: /opt/docker-socket-proxy
socket_proxy_compose_filename: docker-compose.yml

socket_proxy_image: tecnativa/docker-socket-proxy:latest
socket_proxy_container_name: docker-socket-proxy
socket_proxy_restart_policy: unless-stopped
socket_proxy_network_name: "{{ traefik_network_name | default('proxy') }}"

socket_proxy_publish_port: false
socket_proxy_bind_address: 127.0.0.1
socket_proxy_bind_port: "2375"
socket_proxy_endpoint: "http://{{ socket_proxy_container_name }}:2375"
socket_proxy_compose_idempotence_mode: false

socket_proxy_env_defaults:
  AUTH: "0"
  BUILD: "0"
  COMMIT: "0"
  CONFIGS: "0"
  CONTAINERS: "1"
  DISTRIBUTION: "0"
  EVENTS: "1"
  EXEC: "0"
  IMAGES: "1"
  INFO: "1"
  NETWORKS: "1"
  NODES: "0"
  PING: "1"
  PLUGINS: "0"
  POST: "0"
  SECRETS: "0"
  SERVICES: "0"
  SESSION: "0"
  SWARM: "0"
  SYSTEM: "0"
  TASKS: "0"
  VERSION: "1"
  VOLUMES: "1"

socket_proxy_env_overrides: {}
