---
driver:
  name: docker

platforms:
  - name: ubuntu2404-docker
    image: ubuntu:24.04
    pre_build_image: true
    command: /bin/bash -c "while true; do sleep 3600; done"
    privileged: true

provisioner:
  name: ansible
  log: true
  playbooks:
    converge: converge.yml
    verify: verify.yml

scenario:
  name: docker
  test_sequence:
    - destroy
    - create
    - converge
    - idempotence
    - verify
    - destroy

verifier:
  name: ansible
