---
traefik_enable: false

traefik_install_docker: true
traefik_manage_user_group: true
traefik_admin_user: "{{ base_admin_user | default('') }}"

traefik_manage_firewall_rules: true
traefik_firewall_ports:
  - "80"
  - "443"

traefik_stack_root: /opt/traefik
traefik_dynamic_dir: "{{ traefik_stack_root }}/dynamic"
traefik_certs_dir: "{{ traefik_stack_root }}/certs"

traefik_compose_filename: docker-compose.yml
traefik_config_filename: traefik.yml
traefik_dynamic_tls_filename: tls.yml

traefik_image: traefik:v2.11
traefik_container_name: traefik
traefik_network_name: proxy
traefik_restart_policy: unless-stopped

traefik_domain: ""
traefik_dashboard_enable: false
traefik_dashboard_host: "{{ ('traefik.' ~ traefik_domain) if (traefik_domain | length > 0) else '' }}"

traefik_entrypoint_web_address: ":80"
traefik_entrypoint_websecure_address: ":443"
traefik_enable_http_to_https_redirect: true
traefik_log_level: INFO
traefik_enable_access_log: true

traefik_use_origin_cert: false
traefik_origin_cert_filename: origin.crt
traefik_origin_key_filename: origin.key
traefik_origin_cert_content: ""
traefik_origin_key_content: ""
